services:
  - type: web
    name: elevat-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://elevatrehabilitationcenter.com/api
